version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /store/syncthing:/var/syncthing
    networks:
      - micro.internal
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.http_syncthing.entryPoints=web"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.http_syncthing.rule=Host(`syncthing.zarva.me`)"
      - "traefik.http.routers.http_syncthing.service=syncthing"
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
networks:
  micro.internal:
    external:
      name: micro.internal
