version: "2"

services:
  gitea:
    image: gitea/gitea:1.17.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
    hostname: gitea
    container_name: gitea
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - micro.internal
      - postgres.internal
    ports:
      - "22:22"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.http_gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.http_gitea.entryPoints=web"
      - "traefik.http.routers.http_gitea.rule=Host(`gitea.zarva.me`)"

networks:
  postgres.internal:
    external:
      name: postgres.internal
  micro.internal:
    external:
      name: micro.internal
