# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
version: "2"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: 'Europe/Berlin'
      ServerIP: '192.168.1.150'
      WEB_PORT: 1001
      DNSSEC: 'True'
      INTERFACE: eno1
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    hostname: pihole.zarva
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

