version: "2"
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./routing.yaml:/etc/traefik/routing.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
    networks:
      - micro.internal
    container_name: traefik
    environment:
      TZ: 'Europe/Berlin'
    hostname: traefik.zarva
    restart: unless-stopped

networks:
  micro.internal:
    external:
     name: micro.internal
