entryPoints:
  websecure:
    address: ":443"
  web:
    address: ":80"

tls:
  options:
    default:
      sniStrict: true
      minVersion: "VersionTLS12"
      chiperSuites:
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
      - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
  certificates:
    - certFile: /etc/letsencrypt/live/zarva.me/fullchain.pem
      keyFile: /etc/letsencrypt/live/zarva.me/privkey.pem

providers:
  file:
    filename: /etc/traefik/routing.yaml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedbydefault: false
    network: micro.internal

log:
  level: "DEBUG"
