version: '2'

services:

  nextcloud:
    logging: &logging
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
    image: custom_nextcloud
    build:
      context: ./build
      dockerfile: nextcloud_Dockerfile
    volumes:
      - ./data:/var/www/html
      - /store/nextcloud:/var/www/html/data
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: unless-stopped
    user: next
    environment:
      - TZ=Europe/Berlin
    container_name: nextcloud
    hostname: nextcloud.zarva
    networks:
      - nextcloud.internal
      - postgres.internal

  nextcloud_reversproxy:
    image: nextcloud_reversproxy
    build:
      context: ./build
      dockerfile: reversproxy_Dockerfile
    logging: *logging
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud
    restart: unless-stopped
    user: next
    environment:
      - TZ=Europe/Berlin
    container_name: nextcloud_reversproxy
    hostname: nextcloud_server.zarva
    networks:
      - nextcloud.internal
      - micro.internal
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.http_nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=8080"
      - "traefik.http.routers.http_nextcloud.entryPoints=web"
      - "traefik.http.routers.http_nextcloud.rule=Host(`nextcloud.zarva.me`)"

      - "traefik.http.services.collabora.loadbalancer.server.port=8081"
      - "traefik.http.routers.http_collabora.service=collabora"
      - "traefik.http.routers.http_collabora.entryPoints=web"
      - "traefik.http.routers.http_collabora.rule=Host(`collabora.zarva.me`)"

      - "traefik.http.middlewares.nextcloud-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.customframeoptionsvalue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.X-Download-Options=noopen"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.X-Permitted-Cross-Domain-Policies=none"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.Strict-Transport-Security=15552000"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.Referrer-Policy=no-referrer"
      - "traefik.http.middlewares.nextcloud-headers.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.routers.http_nextcloud.middlewares=nextcloud-headers"

  cron:
    build:
      context: ./build
      dockerfile: cron_Dockerfile
    container_name: cron
    restart: unless-stopped
    logging: *logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Berlin

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    logging: *logging
    hostname: collabora
    networks:
      - nextcloud.internal
    cap_add:
      - MKNOD
    environment:
      - TZ=Europe/Beriln
      - domain=nextcloud.zarva.me
      - |
        extra_params=
        --o:ssl.enable=false
        --o:ssl.termination=true
        --o:net.proto=IPv4

networks:
  postgres.internal:
    external:
      name: postgres.internal
  micro.internal:
    external:
      name: micro.internal
  nextcloud.internal:
    external:
      name: nextcloud.internal
