version: '2'
services:
  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    restart: unless-stopped
    #    user: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=xzasdiukh
      - TZ=Europe/Berlin
    container_name: postgres
    hostname: postgres.zarva
    networks:
      - postgres.internal
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

networks:
  postgres.internal:
    external:
      name: postgres.internal
