version: '2'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /store/jellyfin/cache:/cache
      - /store/jellyfin/media:/media
      - /store/jellyfin/media2:/media2
    restart: unless-stopped
    networks:
      - micro.internal
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.http_jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.http_jellyfin.entryPoints=web"
      - "traefik.http.routers.http_jellyfin.rule=Host(`jellyfin.zarva.me`)"

networks:
  micro.internal:
    external:
      name: micro.internal
