version: "2"

services:
  iobroker:
    image: buanet/iobroker:latest
    hostname: iobroker
    container_name: iobroker
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - USBDEVICES=/dev/ttyACM0
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data:/opt/iobroker
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    networks:
      - micro.internal
      - influx.internal
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.http_iobroker.entryPoints=web"
      - "traefik.http.routers.http_iobroker.rule=Host(`iobroker.zarva.me`)"
      - "traefik.http.services.iobroker.loadbalancer.server.port=8081"
      - "traefik.http.routers.http_iobroker.service=iobroker"

      - "traefik.http.routers.http_vis.entryPoints=web"
      - "traefik.http.routers.http_vis.rule=Host(`vis.zarva.me`)"
      - "traefik.http.services.vis.loadbalancer.server.port=8082"
      - "traefik.http.routers.http_vis.service=vis"

networks:
  micro.internal:
    external:
      name: micro.internal
  influx.internal:
    external:
      name: influx.internal
