version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - /store/your_spotify_db:/data/db
    networks:
      - mongo.internal
    restart: unless-stopped
    env_file:
      - .env

networks:
  mongo.internal:
    external:
      name: mongo.internal
